runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

handlers:
- url: /css/(.*\.css)$
  static_files: static/css/\1
  upload: static/css/(.*\.css)$

- url: /html/(.*\.html)$
  static_files: static/html/\1
  upload: static/html/(.*\.html)$

- url: /img/(.*\.(gif|ico|jpg|png|svg|xml|json))$
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|ico|jpg|png|svg|xml|json))$

- url: /js/(.*\.js)$
  static_files: static/js/\1
  upload: static/js/(.*\.js)$

- url: /3p/(.*\.css)$
  static_files: third_party/\1
  upload: third_party/(.*\.css)$

- url: /3p/(.*\.js)$
  static_files: third_party/\1
  upload: third_party/(.*\.js)$

- url: /.*
  script: gir_app_labs_at_aamu.app
